version: '3'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt/fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ./letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem
      - ./letsencrypt/chain.pem:/etc/letsencrypt/chain.pem
      - ./html:/var/www/html
    ports:
      - 80:80
      - 443:443