version: '3'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html
    ports:
      - 80:80
      - 443:443